server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://parkchris0131:beakgugong0131@cluster0.honhdbo.mongodb.net/test?retryWrites=true&w=majority
  oauth2:
    client:
      registration:
        naver:
          client-id: f38KmJuFOYmcHZxuJwMB
          client-secret: 56VX1sKzQa
          redirect-uri: http://localhost:8080/login/oauth/login
          userInfoUrl: https://openapi.naver.com/v1/nid/me
          tokenUrl: https://nid.naver.com/oauth2.0/token
        kakao:
          client-id: 560b92df78c778c1482eeaff5d71c194
          client-secret: UinjBl3UQmuj7d3p1osPMTojUNwkRZOk
          scope:
            # - profile_nickname
            - account_email
          client-name: Kakao
          authorization-grant-type: authorization_code
          client-authentication-method: POST #카카오는 필수 파라미터를 POST로 요청해야됌!
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao #코드를 받는 uri(naver 의 콜백 uri)
      provider: #네이버의 provider는 등록되어 있지 않아 사용자가 등록해야된다.
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: kakao_account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ci1oetc0wppg.ap-northeast-2.rds.amazonaws.com:3306/spam_application
    username: admin
    password: qkrwlstjr1!

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

app:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 799333127259-2e22vu6n71ctc579itbpvpdivoa8am99.apps.googleusercontent.com
      secret: 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
    callback:
      url: http://localhost:8080/login/oauth2/code/google
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/v1/userinfo
  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client:
      id: 560b92df78c778c1482eeaff5d71c194
      secret: UinjBl3UQmuj7d3p1osPMTojUNwkRZOk
    callback:
      url: http://localhost:8080/login/oauth2/code/kakao
    token:
      url: https://kauth.kakao.com/oauth/token
    userinfo:
      url: https://kapi.kakao.com/v2/user/me



security:
  jwt:
    token:
      secret-key: Vu6WXrg3t9
      expire-length: 3600000