server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-rds-instance.cqwxdf1sdeiw.ap-northeast-2.rds.amazonaws.com:3306/my_rds_name
    username: admin
    password: qogustj50

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

app:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 799333127259-2e22vu6n71ctc579itbpvpdivoa8am99.apps.googleusercontent.com
      secret: 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
    callback:
      url: http://localhost:8080/login/oauth2/code/google
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/v1/userinfo


security:
  jwt:
    token:
      secret-key: Vu6WXrg3t9
      expire-length: 3600000